"""empty message

Revision ID: 0400877a77ed
Revises: 
Create Date: 2018-10-05 09:41:41.052809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0400877a77ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=10), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('open', sa.Numeric(precision=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=2), nullable=True),
    sa.Column('pre_close', sa.Numeric(precision=2), nullable=True),
    sa.Column('change', sa.Numeric(precision=2), nullable=True),
    sa.Column('pct_change', sa.Numeric(precision=2), nullable=True),
    sa.Column('vol', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_ts_code'), 'daily', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_ts_code'), table_name='daily')
    op.drop_table('daily')
    # ### end Alembic commands ###
