"""empty message

Revision ID: 438b234e68bd
Revises: 
Create Date: 2018-09-01 02:59:41.146621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438b234e68bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('pe', sa.String(length=50), nullable=True),
    sa.Column('outstanding', sa.BigInteger(), nullable=True),
    sa.Column('totals', sa.BigInteger(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('liquid_assets', sa.BigInteger(), nullable=True),
    sa.Column('fixed_assets', sa.BigInteger(), nullable=True),
    sa.Column('esp', sa.Integer(), nullable=True),
    sa.Column('bvps', sa.Integer(), nullable=True),
    sa.Column('pb', sa.Integer(), nullable=True),
    sa.Column('time_to_market', sa.Date(), nullable=True),
    sa.Column('undp', sa.Integer(), nullable=True),
    sa.Column('perundp', sa.Integer(), nullable=True),
    sa.Column('rev', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Integer(), nullable=True),
    sa.Column('npr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_basic_code'), 'stock_basic', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_basic_code'), table_name='stock_basic')
    op.drop_table('stock_basic')
    # ### end Alembic commands ###
